import Head from 'next/head'
import Image from 'next/image'
import QuickBtn from '../presentation/components/features/quick/button/QuickBtn'
import s from '../styles/home.module.scss'

export default function Home() {
  return <>
    <Head>
      <title>Quick Pop Up</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>

    <main className={s.layout}>
      <nav className={s.sidenav}></nav>
      <section className={s.content}>
        <nav className={s.nav}>
          <div className={s.search_wrapper}>
            <Image src="./icons/magnifier_bold.svg" alt="search icon" width={17} height={17} />
          </div>
        </nav>


        <QuickBtn />
      </section>
    </main>
  </>
}
